name: Create a RELEASE
on: 
  workflow_dispatch:

defaults:
  shell: bash

jobs:
  get-latest-tag-name-release:
    name: get latest tag name release
    runs-on: ubuntu-latest
    outputs:
      LASTEST_TAG: ${{ steps.get-latest-tag.outputs.LATEST_TAG }}
    steps:
      - id: get-latest-tag
        name: Get project RELEASE
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ls -lah
          LATEST_TAG=$(gh release list -O desc --json tagName --jq ".[].tagName" -L 1)
          echo "LATEST_TAG=$LAST_RELEASE" >> "$GITHUB_OUTPUT"

  get-markdown-exemple:
    name: get markdown exemple
    runs-on: ubuntu-latest
    outputs:
      RELEASE_EXEMPLE: ${{ steps.get-markdown.outputs.RELEASE_EXEMPLE }}
    steps:
      - name: Get repo access
        uses: actions/checkout@v4

      - name: testing
        run: ls -lah

      - id: get-markdown
        name: Get Release
        run: echo "RELEASE_EXEMPLE=$(cat .github/release.md)" >> "$GITHUB_OUTPUT"

  create-release:
    name: generate release
    runs-on: ubuntu-latest
    needs: [get-latest-tag-name-release, get-markdown-exemple]
    env:
      RELEASE_EXEMPLE: ${{ steps.get-markdown.RELEASE_EXEMPLE }}
      LATEST_TAG: ${{ steps.get-latest-tag.outputs.LATEST_TAG }}
    steps:
      - name: show envs
        run: |
          echo "$RELEASE_EXEMPLE"
          echo "$LATEST_TAG"

      - id: create-template
        name: Create a template
        run: |
          TEMPLATE=$(echo "$RELEASE_EXEMPLE" | sed -E "s/@\{(.+)\}\s(.+)/git log --format='\\2' "$LATEST_TAG"...HEAD | grep -Pi '\\1'/gie")
          echo "TEMPLATE=$TEMPLATE" >> "$GITHUB_OUTPUT"

      - name: Create a release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: echo ${{ steps.create-template.outputs.TEMPLATE }} | gh create release v1.0.0 -F - 
