name: teste
run-name: testeeee
on:
  workflow_dispatch:
    inputs:
      start-tag:
        description: 'Type START tag to show commits:'
        type: string
        required: false
      tag-end:
        description: 'Type END tag to show commits:'
        type: string
        required: true
jobs:
  teste-job:
    runs-on: ubuntu-latest
    steps:
      - name: teste
        run: |
          echo ${{ inputs.tag-start }}
          echo ${{ inputs.tag-end }}
