name: Fill last published release
on: 
  workflow_dispatch:
  push:
    branches:
      - config/actions
defaults:
  run:
    shell: bash
jobs:
  get-last-release:
    name: Get last release
    runs-on: ubuntu-24.02
    steps:
      - name: Get all tags
        run: echo "${{ github.api_url }}/repost/MauMuller/releases"
