name: Fill last published release
on: workflow_dispatch

defaults:
  run:
    shell: bash

# Obter último commit com release
# pegar todos os commits feitos a partir desse
# preencher a nova release criada

jobs:
  get-last-release:
    name: Get last release
    runs-on: ubuntu-24.02
    steps:
      - name: Get all tags
        run: echo "${{ github.api_url }}/repost/MauMuller/releases"
