changelog:
  categories:
    - title: Features 
      labels:
        - feature
    - title: Refactores
      labels:
        - refactor
    - title: Bugfixs
      labels:
        - bugfix
    - title: Others
      labels:
        - '*'
